version: '3.6'

services:
  compress-image:
    container_name: compress-image
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    volumes:
      - $HOME/.aws/:/root/.aws/
    ports:
      - '9000:8080'
    env_file:
      - .env
